name:                EOP
version:             0.1.0.0
github:              "githubuser/EOP"
license:             BSD-3-Clause
author:              "IgorErin"
maintainer:          "example@example.com"
copyright:           "2023 IgorErin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/EOP#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies: 
  - array 
  - base
  - bytestring 
  - containers
  build-tool-depends: 
  - alex 
  - happy

executables:
  EOP-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EOP

tests:
  EOP-test:
    main:                Main.hs
    source-dirs:         test
    other-modules:
      - Tests.Let.Lexer
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - EOP
    - tasty 
    - tasty-hunit
